version: '3'
services:
  grpc-service:
    build: ./grpc-square-service
    image: bayvao/grpc-square-service
  rest-service:
    build: ./rest-square-service
    image: bayvao/rest-square-service
  aggregator-service:
    build: ./aggregator-service
    image: bayvao/aggregator-service
    ports:
      - 8080:8080
    environment:
      - GRPC_CLIENT_SQUARE_ADDRESS=static://grpc-service:6565
      - REST_SQUARE_SERVICE_ENDPOINT=http://rest-service:7575